### PR TITLE
Added lazy loading of images

### PR DESCRIPTION
**Pull request by coderwassananmol**

### CODE REVIEW

**Comment by r0mflip** [comment]
Can you please rebase your code over master and make the required changes. Also move the attribute to the end as it feels neat.

**Comment by coderwassananmol** [comment]
> Lazy loading not required for footer, coc and banner images

Let me know if the latest PR would work! :)

**Comment by notlmn** [comment]
👍 Proceed after rebase.

**Comment by coderwassananmol** [comment]
> 👍 Proceed after rebase.

Do I need to rebase with master? There are no conflicts per se.

**Comment by notlmn** [comment]
> Do I need to rebase with master? There are no conflicts per se.

There's no issues, but it helps us have a clean git history.

**Comment by coderwassananmol** [comment]
> > Do I need to rebase with master? There are no conflicts per se.
> 
> There's no issues, but it helps us have a clean git history.

I have already made a merge commit. Rebasing with upstream/master is creating conflicts. Can you merge this PR with rebase strategy at your end?

**Comment by r0mflip** [comment]
@coderwassananmol There seems to be a layout issue, need to test. As we are AFK expect late replies.

**Comment by coderwassananmol** [comment]
> @coderwassananmol There seems to be a layout issue, need to test. As we are AFK expect late replies.

No issues. Let me know when you test.

**Pull request merged**
